export const ROUTES = {
  HOME: '/',
  APPS: '/apps',
  APP_DETAIL: (slug: string) => `/apps/${slug}`,
  BLOG: '/blog',
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  HELP: '/help',
  HELP_ARTICLE: (category: string, slug: string) => `/help/${category}/${slug}`,
  SUPPORT: '/support',
  ABOUT: '/about',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  ACCESSIBILITY: '/accessibility',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  LIBRARY: '/library',
  SETTINGS: '/settings',
  ADMIN: {
    ROOT: '/admin',
    APPS: '/admin/apps',
    BLOG: '/admin/blog',
    HELP: '/admin/help',
    SUPPORT: '/admin/support',
    MEDIA: '/admin/media',
    USERS: '/admin/users',
    AUDIT: '/admin/audit',
    AUDIT_LOGS: '/admin/audit',
    ANALYTICS: '/admin',
  },
} as const;
